CREATE TABLE IF NOT EXISTS post (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(100) NOT NULL,
    content    VARCHAR(255) NOT NULL,
    category   VARCHAR(50),
    owner      VARCHAR(50) NOT NULL,
    created_at VARCHAR(100) NOT NULL,
    updated_at VARCHAR(100) NOT NULL
);