CREATE TABLE post (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(100) NOT NULL,
    content    VARCHAR(255) NOT NULL,
    category   VARCHAR(50),
    tags       JSON,
    created_at VARCHAR(100) NOT NULL,
    updated_at VARCHAR(100) NOT NULL
);